# GoReleaser configuration
# Documentation: https://goreleaser.com

version: 2

before:
  hooks:
    - go mod tidy

builds:
  - id: etcdtui
    main: ./cmd/etcdtui
    binary: etcdtui
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.ShortCommit}}
      - -X main.buildTime={{.Date}}

archives:
  - id: default
    format: tar.gz
    name_template: >-
      {{ .ProjectName }}-
      {{- .Version }}-
      {{- .Os }}-
      {{- .Arch }}
    files:
      - README.md
      - LICENSE

checksum:
  name_template: 'checksums.txt'

snapshot:
  version_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^chore:'
      - Merge pull request
      - Merge branch

brews:
  - name: etcdtui
    repository:
      owner: alexandr
      name: homebrew-tap
      token: "{{ .Env.HOMEBREW_TAP_TOKEN }}"
    directory: Formula
    homepage: "https://github.com/alexandr/etcdtui"
    description: "Interactive terminal UI for etcd"
    license: "MIT"
    install: |
      bin.install "etcdtui"
    test: |
      system "#{bin}/etcdtui", "--version"

release:
  github:
    owner: alexandr
    name: etcdtui
  draft: false
  prerelease: auto
  name_template: "{{.ProjectName}} v{{.Version}}"
