# Homebrew formula template for etcdtui
# This file is auto-generated by goreleaser during releases.
# To use manually, create a tap repository: github.com/alexandr/homebrew-tap
# and place this file in the Formula/ directory.

class Etcdtui < Formula
  desc "Interactive terminal UI for etcd"
  homepage "https://github.com/alexandr/etcdtui"
  license "MIT"

  # Update these values for each release
  version "0.1.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/alexandr/etcdtui/releases/download/v#{version}/etcdtui-#{version}-darwin-arm64.tar.gz"
      sha256 "REPLACE_WITH_ACTUAL_SHA256"
    else
      url "https://github.com/alexandr/etcdtui/releases/download/v#{version}/etcdtui-#{version}-darwin-amd64.tar.gz"
      sha256 "REPLACE_WITH_ACTUAL_SHA256"
    end
  end

  on_linux do
    if Hardware::CPU.arm?
      url "https://github.com/alexandr/etcdtui/releases/download/v#{version}/etcdtui-#{version}-linux-arm64.tar.gz"
      sha256 "REPLACE_WITH_ACTUAL_SHA256"
    else
      url "https://github.com/alexandr/etcdtui/releases/download/v#{version}/etcdtui-#{version}-linux-amd64.tar.gz"
      sha256 "REPLACE_WITH_ACTUAL_SHA256"
    end
  end

  def install
    bin.install "etcdtui"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/etcdtui --version")
  end
end
